#region Using Directives

using System;
using System.Threading;
using System.Threading.Tasks;
using QuoteConversionReportAutomation.Models;
using QuoteConversionReportAutomation.Orchestrators;

#endregion

namespace QuoteConversionReportAutomation.Services.Interfaces
{
    #region Interface Definition
    /// <summary>
    /// Defines the contract for a service that orchestrates the entire Excel report processing workflow.
    /// It coordinates various specialised services to transform a raw data file into a final, processed report.
    /// </summary>
    public interface IExcelProcessingOrchestrator
    {
        #region Methods
        /// <summary>
        /// Asynchronously orchestrates the processing of a raw Excel report. This includes copying data to a template,
        /// filtering, running analysis, generating specialised sheets, and saving the final report.
        /// </summary>
        /// <param name="selectedFinYear">The financial year string (e.g., "2023_24") relevant for the report.</param>
        /// <param name="reportType">The type of report being processed, which dictates specific logic.</param>
        /// <param name="sourceFilePath">The full path to the raw source Excel file generated by Crystal Reports.</param>
        /// <param name="sourceSheetNameConfigKey">The configuration key for the name of the sheet in the source file.</param>
        /// <param name="baseFileSaveLocation">The base directory where the final processed report will be saved.</param>
        /// <param name="templateFilePath">The full path to the Excel template file that will be used.</param>
        /// <param name="destinationDataSheetNameConfigKey">The configuration key for the name of the sheet in the template where data is copied.</param>
        /// <param name="startRow">The starting row (1-based) in the source sheet from which to begin copying data.</param>
        /// <param name="startCol">The starting column (1-based) in the source sheet from which to begin copying data.</param>
        /// <param name="reportDate">The primary date for the report, used for filename generation and internal logic.</param>
        /// <param name="manualParams">Optional parameters for a manually triggered report, for additional context.</param>
        /// <param name="autoRunDef">Optional definition for an automatically triggered report.</param>
        /// <param name="cancellationToken">A token to monitor for cancellation requests from the user.</param>
        /// <returns>
        /// A task that represents the asynchronous operation. The task result is the full path to the
        /// final processed Excel file, or null if the processing fails or is cancelled.
        /// </returns>
        Task<string?> ProcessExcelReportAsync(
            string selectedFinYear,
            ReportType reportType,
            string sourceFilePath,
            string sourceSheetNameConfigKey,
            string baseFileSaveLocation,
            string templateFilePath,
            string destinationDataSheetNameConfigKey,
            int startRow,
            int startCol,
            DateTime reportDate,
            ManualReportParameters? manualParams,
            AutoReportDefinition? autoRunDef,
            CancellationToken cancellationToken);
        #endregion
    }
    #endregion
}